<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WB0005-1" name="Firefox_Test5" tests="17" failures="14" timestamp="17 Oct 2016 19:03:12 GMT" time="5134.407" errors="0">
  <testcase name="test" time="1604.925" classname="com.autotest.testcases.UserRegistration"/>
  <testcase name="test" time="12.715" classname="com.autotest.testcases.YYS008_RewardAdd">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_RewardAdd.test(YYS008_RewardAdd.java:153)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="419.212" classname="com.autotest.testcases.Project_Release_YYS008"/>
  <testcase name="test" time="582.953" classname="com.autotest.testcases.YYS008_UserInvest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_UserInvest.test(YYS008_UserInvest.java:382)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="321.727" classname="com.autotest.testcases.YYS008_GenPayPlan"/>
  <testcase name="Test" time="550.09" classname="com.autotest.testcases.YYS008_PayMent">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_PayMent.Test(YYS008_PayMent.java:348)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Test -->
  <testcase name="test" time="264.565" classname="com.autotest.testcases.YYS008_FastCashProject_U17">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_FastCashProject_U17.test(YYS008_FastCashProject_U17.java:268)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="57.201" classname="com.autotest.testcases.YYS008_InvestSDT_U17">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_InvestSDT_U17.test(YYS008_InvestSDT_U17.java:520)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="50.157" classname="com.autotest.testcases.YYS008_CashEnd_ViewAccount_U17">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_CashEnd_ViewAccount_U17.test(YYS008_CashEnd_ViewAccount_U17.java:184)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="57.159" classname="com.autotest.testcases.YYS008_CashEnd_ViewAccount_U18">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_CashEnd_ViewAccount_U18.test(YYS008_CashEnd_ViewAccount_U18.java:159)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="52.993" classname="com.autotest.testcases.YYS008_FastCashProject_U21">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_FastCashProject_U21.test(YYS008_FastCashProject_U21.java:242)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="169.95" classname="com.autotest.testcases.YYS008_InvestSDT_U21">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_InvestSDT_U21.test(YYS008_InvestSDT_U21.java:425)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="40.578" classname="com.autotest.testcases.YYS008_CashEnd_ViewAccount_U21">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_CashEnd_ViewAccount_U21.test(YYS008_CashEnd_ViewAccount_U21.java:148)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="47.76" classname="com.autotest.testcases.YYS008_FastCashProject_U24">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_FastCashProject_U24.test(YYS008_FastCashProject_U24.java:246)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="166.134" classname="com.autotest.testcases.YYS008_InvestSDT_U24">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_InvestSDT_U24.test(YYS008_InvestSDT_U24.java:405)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="35.847" classname="com.autotest.testcases.YYS008_CashEnd_ViewAccount_U24">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_CashEnd_ViewAccount_U24.test(YYS008_CashEnd_ViewAccount_U24.java:168)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="464.664" classname="com.autotest.testcases.YYS008_Repay_Business">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS008_Repay_Business.test(YYS008_Repay_Business.java:293)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- Firefox_Test5 -->
