<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WB0005-1" name="Firefox_Test3" tests="5" failures="5" timestamp="17 Oct 2016 17:05:13 GMT" time="1327.445" errors="0">
  <testcase name="test" time="36.203" classname="com.autotest.testcases.Project_Release_YYS005">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.Project_Release_YYS005.test(Project_Release_YYS005.java:416)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="653.221" classname="com.autotest.testcases.YYS005_UserInvest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS005_UserInvest.test(YYS005_UserInvest.java:374)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="22.924" classname="com.autotest.testcases.YYS005_GenPayPlan">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS005_GenPayPlan.test(YYS005_GenPayPlan.java:211)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="Test" time="41.066" classname="com.autotest.testcases.YYS005_Payment">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS005_Payment.Test(YYS005_Payment.java:331)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Test -->
  <testcase name="test" time="512.242" classname="com.autotest.testcases.YYS005_Repay_Business">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS005_Repay_Business.test(YYS005_Repay_Business.java:110)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- Firefox_Test3 -->
