<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WB0005-1" name="Firefox_Test2" tests="6" failures="6" timestamp="17 Oct 2016 14:13:20 GMT" time="1308.454" errors="0">
  <testcase name="test" time="429.222" classname="com.autotest.testcases.Project_Release_YYS002">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.Project_Release_YYS002.test(Project_Release_YYS002.java:409)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="326.227" classname="com.autotest.testcases.YYS002_UserInvest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS002_UserInvest.test(YYS002_UserInvest.java:430)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="26.054" classname="com.autotest.testcases.YYS002_GenPayPlan">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS002_GenPayPlan.test(YYS002_GenPayPlan.java:211)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="Test" time="44.089" classname="com.autotest.testcases.YYS002_Payment">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS002_Payment.Test(YYS002_Payment.java:331)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Test -->
  <testcase name="Test" time="143.418" classname="com.autotest.testcases.YYS002_EarlyRepay_GenPayPlan">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS002_EarlyRepay_GenPayPlan.Test(YYS002_EarlyRepay_GenPayPlan.java:461)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Test -->
  <testcase name="test" time="263.532" classname="com.autotest.testcases.YYS002_Repay_Business">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS002_Repay_Business.test(YYS002_Repay_Business.java:293)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- Firefox_Test2 -->
