<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WB0005-1" name="Firefox_Test4" tests="9" failures="8" timestamp="17 Oct 2016 17:37:37 GMT" time="1944.018" errors="0">
  <testcase name="test" time="661.119" classname="com.autotest.testcases.UserRegistration"/>
  <testcase name="test" time="33.303" classname="com.autotest.testcases.Project_Release_YYS007">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.Project_Release_YYS007.test(Project_Release_YYS007.java:409)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="663.143" classname="com.autotest.testcases.YYS007_UserInvest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS007_UserInvest.test(YYS007_UserInvest.java:396)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="32.628" classname="com.autotest.testcases.YYS007_GenPayPlan">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS007_GenPayPlan.test(YYS007_GenPayPlan.java:211)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="Test" time="42.98" classname="com.autotest.testcases.YYS007_PayMent">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS007_PayMent.Test(YYS007_PayMent.java:333)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Test -->
  <testcase name="test" time="60.549" classname="com.autotest.testcases.YYS007_FastCashProject">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS007_FastCashProject.test(YYS007_FastCashProject.java:184)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="34.53" classname="com.autotest.testcases.YYS007_InvestSDT">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS007_InvestSDT.test(YYS007_InvestSDT.java:397)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="34.948" classname="com.autotest.testcases.YYS007_CashEnd_ViewAccount">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS007_CashEnd_ViewAccount.test(YYS007_CashEnd_ViewAccount.java:162)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="250.705" classname="com.autotest.testcases.YYS007_Repay_Business">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.autotest.testcases.YYS007_Repay_Business.test(YYS007_Repay_Business.java:285)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- Firefox_Test4 -->
